const ANIMALS_DATA = {
    "leao": {
        "n": "LEÃO",
        "c": "PLEXO SOLAR",
        "d": "Soberania e Coragem. O domínio do Eu consciente sobre os instintos primordiais. Arquétipo do Rei/Guardião presente em todas as culturas.",
        "a": 0.9,
        "s": 0.3,
        "i": 0.6,
        "p": "SOLAR",
        "e": ["FOGO"],
        "f": "VOLIÇÃO"
    },
    "aguia": {
        "n": "ÁGUIA",
        "c": "TERCEIRO OLHO",
        "d": "Visão Transpessoal. A capacidade de observar a vida de uma perspetiva elevada. Mensageira divina na mitologia grega e nativa americana.",
        "a": 0.7,
        "s": 0.5,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["AR"],
        "f": "INTUIÇÃO"
    },
    "lobo": {
        "n": "LOBO",
        "c": "GARGANTA",
        "d": "Inteligência Social. O mestre do equilíbrio entre a matilha e a autonomia individual. Professor e guia nas tradições xamânicas.",
        "a": 0.6,
        "s": 0.4,
        "i": 0.7,
        "p": "LUNAR",
        "e": ["TERRA", "AR"],
        "f": "SOCIAL"
    },
    "coruja": {
        "n": "CORUJA",
        "c": "COROA",
        "d": "Sabedoria Oculta. A faculdade de navegar no inconsciente e ver a verdade nas sombras. Símbolo de Atena na Grécia Antiga.",
        "a": 0.5,
        "s": 0.8,
        "i": 0.9,
        "p": "LUNAR",
        "e": ["AR", "ESPIRITO"],
        "f": "SABEDORIA"
    },
    "urso": {
        "n": "URSO",
        "c": "RAIZ",
        "d": "Introspeção e Cura. A força que provém do silêncio interior e da renovação cíclica. Animal de poder para xamãs siberianos.",
        "a": 0.4,
        "s": 0.6,
        "i": 0.7,
        "p": "LUNAR",
        "e": ["TERRA"],
        "f": "INTROSPECÇÃO"
    },
    "baleia": {
        "n": "BALEIA",
        "c": "CORAÇÃO",
        "d": "Memória Ancestral. Guardiã das frequências emocionais profundas do planeta. Criadora de mundos na mitologia polinésia.",
        "a": 0.3,
        "s": 0.7,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["AGUA"],
        "f": "MEMORIA_COLETIVA"
    },
    "serpente": {
        "n": "SERPENTE",
        "c": "SACRO",
        "d": "Transmutação Vital. Energia Kundalini em constante renovação e transformação. Símbolo de cura e renascimento universal.",
        "a": 0.6,
        "s": 0.9,
        "i": 0.8,
        "p": "SOLAR",
        "e": ["TERRA", "FOGO"],
        "f": "TRANSFORMACAO"
    },
    "tartaruga": {
        "n": "TARTARUGA",
        "c": "RAIZ",
        "d": "Resiliência Histórica. A sabedoria de quem caminha no tempo certo da Terra. Suporta o mundo em várias mitologias.",
        "a": 0.2,
        "s": 0.3,
        "i": 0.9,
        "p": "LUNAR",
        "e": ["TERRA", "AGUA"],
        "f": "PACIENTE"
    },
    "elefante": {
        "n": "ELEFANTE",
        "c": "RAIZ",
        "d": "Paciência e Realeza. Força imensa baseada na ancestralidade e na proteção. Representação de Ganesha no hinduísmo.",
        "a": 0.5,
        "s": 0.4,
        "i": 0.8,
        "p": "SOLAR",
        "e": ["TERRA"],
        "f": "MEMORIA_ANCESTRAL"
    },
    "tubarao": {
        "n": "TUBARÃO",
        "c": "SACRO",
        "d": "Instinto Implacável. Determinação focada e superação de medos abissais. Guia nos oceanos do inconsciente.",
        "a": 0.8,
        "s": 0.7,
        "i": 0.6,
        "p": "SOLAR",
        "e": ["AGUA"],
        "f": "INSTINTO_PURO"
    },
    "pantera": {
        "n": "PANTERA",
        "c": "SACRO",
        "d": "Mistério e Agilidade. Movimento silencioso entre os mundos visível e invisível. Guardiã dos segredos noturnos.",
        "a": 0.7,
        "s": 0.9,
        "i": 0.7,
        "p": "LUNAR",
        "e": ["FOGO", "NOITE"],
        "f": "MISTERIO"
    },
    "colibri": {
        "n": "COLIBRI",
        "c": "CORAÇÃO",
        "d": "Alegria Efêmera. Capacidade de extrair beleza de cada momento passageiro. Mensageiro de amor nas culturas andinas.",
        "a": 0.3,
        "s": 0.2,
        "i": 0.5,
        "p": "SOLAR",
        "e": ["AR", "LUZ"],
        "f": "ALEGRIA_EFEMERA"
    },
    "golfinho": {
        "n": "GOLFINHO",
        "c": "GARGANTA",
        "d": "Comunicação Lúdica. Inteligência social aliada à liberdade criativa. Guia de almas na mitologia grega.",
        "a": 0.5,
        "s": 0.3,
        "i": 0.7,
        "p": "SOLAR",
        "e": ["AGUA", "AR"],
        "f": "COMUNICACAO_LUDICA"
    },
    "castor": {
        "n": "CASTOR",
        "c": "RAIZ",
        "d": "Construção Prática. Transformação do ambiente através do trabalho paciente e determinado. Arquétipo do Construtor.",
        "a": 0.4,
        "s": 0.2,
        "i": 0.6,
        "p": "SOLAR",
        "e": ["TERRA", "AGUA"],
        "f": "CONSTRUCAO_PRATICA"
    },
    "raposa": {
        "n": "RAPOSA",
        "c": "TERCEIRO OLHO",
        "d": "Astúcia Intuitiva. Percepção aguçada para oportunidades ocultas. Trickster e professor em várias culturas.",
        "a": 0.6,
        "s": 0.8,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["TERRA", "AR"],
        "f": "ASTUCIA_INTUITIVA"
    },
    "tigre": {
        "n": "TIGRE",
        "c": "PLEXO SOLAR",
        "d": "Foco e Poder. Energia concentrada para ações decisivas e protegidas. Símbolo real na Ásia, protetor contra espíritos.",
        "a": 0.9,
        "s": 0.6,
        "i": 0.5,
        "p": "SOLAR",
        "e": ["FOGO"],
        "f": "FOCO_PODEROSO"
    },
    "corvo": {
        "n": "CORVO",
        "c": "COROA",
        "d": "Magia e Transformação. Mensageiro entre mundos, detentor de memórias ancestrais. Olho de Odin na mitologia nórdica.",
        "a": 0.5,
        "s": 0.8,
        "i": 0.9,
        "p": "LUNAR",
        "e": ["AR", "ESPIRITO"],
        "f": "MAGIA_TRANSFORMADORA"
    },
    "cavalo": {
        "n": "CAVALO",
        "c": "SACRO",
        "d": "Liberdade e Paixão. Força vital que corre em direção ao horizonte. Pégaso na Grécia, transporte de deuses e heróis.",
        "a": 0.7,
        "s": 0.5,
        "i": 0.7,
        "p": "SOLAR",
        "e": ["TERRA", "AR"],
        "f": "LIBERDADE_PAIXAO"
    },
    "gato": {
        "n": "GATO",
        "c": "TERCEIRO OLHO",
        "d": "Independência Mística. Equilíbrio entre carinho e autonomia, visão noturna. Bastet no Egito, guardiã do lar.",
        "a": 0.6,
        "s": 0.7,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["NOITE", "MISTERIO"],
        "f": "INDEPENDENCIA_MISTICA"
    },
    "borboleta": {
        "n": "BORBOLETA",
        "c": "SACRO",
        "d": "Metamorfose e Alma. Transformação radical, beleza efêmera. Psiquê na Grécia, símbolo da alma em muitas culturas.",
        "a": 0.3,
        "s": 0.9,
        "i": 0.9,
        "p": "LUNAR",
        "e": ["AR", "TRANSFORMACAO"],
        "f": "METAMORFOSE_ALMA"
    },
    "veado": {
        "n": "VEADO",
        "c": "CORAÇÃO",
        "d": "Sensibilidade e Gentileza. Conexão profunda com a natureza e ciclos. Símbolo de Cristo e renascimento espiritual.",
        "a": 0.2,
        "s": 0.3,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["TERRA", "LUZ"],
        "f": "SENSIBILIDADE_GENTILEZA"
    },
    "falcão": {
        "n": "FALCÃO",
        "c": "TERCEIRO OLHO",
        "d": "Foco e Precisão. Visão aguçada para detalhes importantes. Horus no Egito, representação do sol e realeza.",
        "a": 0.8,
        "s": 0.4,
        "i": 0.7,
        "p": "SOLAR",
        "e": ["AR", "FOGO"],
        "f": "FOCO_PRECISAO"
    },
    "cisne": {
        "n": "CISNE",
        "c": "GARGANTA",
        "d": "Graça e Transformação Interior. Beleza que emerge do caos. Zeus como cisne, símbolo de pureza e fidelidade.",
        "a": 0.4,
        "s": 0.6,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["AGUA", "AR"],
        "f": "GRACA_TRANSFORMACAO"
    },
    "touro": {
        "n": "TOURO",
        "c": "RAIZ",
        "d": "Força Terrena e Determinação. Poder de manifestação material. Ápis no Egito, símbolo de fertilidade e poder.",
        "a": 0.7,
        "s": 0.5,
        "i": 0.6,
        "p": "SOLAR",
        "e": ["TERRA"],
        "f": "FORCA_TERRENA"
    },
    "cão": {
        "n": "CÃO",
        "c": "CORAÇÃO",
        "d": "Lealdade e Proteção. Fidelidade incondicional, guardião entre mundos. Anúbis no Egito, Cérbero na Grécia.",
        "a": 0.5,
        "s": 0.3,
        "i": 0.7,
        "p": "SOLAR",
        "e": ["TERRA", "FOGO"],
        "f": "LEALDADE_PROTECAO"
    },
    "aranha": {
        "n": "ARANHA",
        "c": "TERCEIRO OLHO",
        "d": "Criatividade Tecelã. Arte de tecer conexões e padrões complexos. Criadora do mundo em culturas nativas americanas.",
        "a": 0.4,
        "s": 0.8,
        "i": 0.9,
        "p": "LUNAR",
        "e": ["ETER", "CONEXAO"],
        "f": "CRIATIVIDADE_TECELA"
    },
    "morcego": {
        "n": "MORCEGO",
        "c": "TERCEIRO OLHO",
        "d": "Percepção Sônica. Navegação pelo invisível através de ecos. Símbolo de renascimento em culturas mesoamericanas.",
        "a": 0.3,
        "s": 0.9,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["NOITE", "AR"],
        "f": "PERCEPCAO_SONICA"
    },
    "abelha": {
        "n": "ABELHA",
        "c": "PLEXO SOLAR",
        "d": "Comunidade e Prosperidade. Trabalho coletivo, doçura compartilhada. Mensageira dos deuses na Grécia Antiga.",
        "a": 0.2,
        "s": 0.1,
        "i": 0.6,
        "p": "SOLAR",
        "e": ["AR", "TERRA"],
        "f": "COMUNIDADE_PROSPERIDADE"
    },
    "formiga": {
        "n": "FORMIGA",
        "c": "RAIZ",
        "d": "Persistência Coletiva. Disciplina, trabalho em equipe e visão de longo prazo. Esopo, lição de previsão e trabalho.",
        "a": 0.1,
        "s": 0.2,
        "i": 0.5,
        "p": "SOLAR",
        "e": ["TERRA"],
        "f": "PERSISTENCIA_COLETIVA"
    },
    "jacare": {
        "n": "JACARÉ",
        "c": "RAIZ",
        "d": "Paciência Ancestral. Força primal que aguarda o momento exato. Símbolo de criação e paciência em culturas africanas.",
        "a": 0.3,
        "s": 0.7,
        "i": 0.7,
        "p": "LUNAR",
        "e": ["AGUA", "TERRA"],
        "f": "PACIENCIA_ANCESTRAL"
    },
    "lontra": {
        "n": "LONTRA",
        "c": "CORAÇÃO",
        "d": "Jogo e Alegria. Arte de encontrar felicidade nas pequenas coisas. Trickster brincalhão em várias tradições.",
        "a": 0.3,
        "s": 0.2,
        "i": 0.6,
        "p": "SOLAR",
        "e": ["AGUA"],
        "f": "JOGO_ALEGRIA"
    },
    "salamandra": {
        "n": "SALAMANDRA",
        "c": "SACRO",
        "d": "Regeneração e Adaptação. Capacidade de renascer das cinzas. Espírito do fogo na alquimia medieval.",
        "a": 0.4,
        "s": 0.8,
        "i": 0.9,
        "p": "SOLAR",
        "e": ["FOGO", "AGUA"],
        "f": "REGENERACAO_ADAPTACAO"
    },
    "caranguejo": {
        "n": "CARANGUEJO",
        "c": "SACRO",
        "d": "Proteção e Ciclos Lunares. Movimento lateral inteligente, conexão com marés emocionais. Símbolo do zodíaco.",
        "a": 0.2,
        "s": 0.6,
        "i": 0.7,
        "p": "LUNAR",
        "e": ["AGUA", "LUA"],
        "f": "PROTECAO_CICLOS"
    },
    "fênix": {
        "n": "FÊNIX",
        "c": "CORAÇÃO",
        "d": "Ressurreição e Renovação. Capacidade de renascer das cinzas, transformação total. Símbolo de imortalidade universal.",
        "a": 0.5,
        "s": 0.9,
        "i": 1.0,
        "p": "SOLAR",
        "e": ["FOGO", "ESPIRITO"],
        "f": "RESSURREICAO_RENOVACAO"
    },
    "dragão": {
        "n": "DRAGÃO",
        "c": "COROA",
        "d": "Poder Cósmico e Sabedoria. Força elemental, guardião de tesouros. Símbolo de poder na China, força na Europa.",
        "a": 0.9,
        "s": 0.7,
        "i": 0.9,
        "p": "SOLAR",
        "e": ["FOGO", "AR", "TERRA", "AGUA"],
        "f": "PODER_COSMICO"
    },
    "lince": {
        "n": "LINCE",
        "c": "TERCEIRO OLHO",
        "d": "Visão Noturna e Discrição. Capacidade de ver o invisível com aguçada percepção. Guardião de segredos nas florestas.",
        "a": 0.6,
        "s": 0.7,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["TERRA", "NOITE"],
        "f": "PERCEPCAO_AGUÇADA"
    },
    "condor": {
        "n": "CONDOR",
        "c": "COROA",
        "d": "Transcendência e Purificação. Conexão com o divino, limpeza espiritual. Mensageiro entre céu e terra nas culturas andinas.",
        "a": 0.4,
        "s": 0.8,
        "i": 0.9,
        "p": "SOLAR",
        "e": ["AR", "ESPIRITO"],
        "f": "TRANSCENDENCIA"
    },
    "tucano": {
        "n": "TUCANO",
        "c": "GARGANTA",
        "d": "Comunicação Vibrante e Comunidade. Alegria coletiva e expressão colorida. Símbolo de comunicação nas florestas tropicais.",
        "a": 0.5,
        "s": 0.3,
        "i": 0.6,
        "p": "SOLAR",
        "e": ["AR", "LUZ"],
        "f": "COMUNICACAO_VIBRANTE"
    },
    "polvo": {
        "n": "POLVO",
        "c": "SACRO",
        "d": "Adaptabilidade e Inteligência Emocional. Capacidade de mudar forma e sentir profundamente. Mestre da camuflagem nos oceanos.",
        "a": 0.3,
        "s": 0.8,
        "i": 0.9,
        "p": "LUNAR",
        "e": ["AGUA", "MUDANCA"],
        "f": "ADAPTABILIDADE_EMOCIONAL"
    },
    "crocodilo": {
        "n": "CROCODILO",
        "c": "RAIZ",
        "d": "Paciência Primitiva e Sobrevivência. Força ancestral que atravessa eras. Símbolo de fertilidade no antigo Egito.",
        "a": 0.4,
        "s": 0.8,
        "i": 0.7,
        "p": "SOLAR",
        "e": ["AGUA", "TERRA"],
        "f": "SOBREVIVENCIA_PRIMORDIAL"
    },
    "hiena": {
        "n": "HIENA",
        "c": "SACRO",
        "d": "Riso e Transformação da Morte. Capacidade de rir do perigo, transformadora de matéria. Figura ambígua na mitologia africana.",
        "a": 0.5,
        "s": 0.9,
        "i": 0.7,
        "p": "LUNAR",
        "e": ["TERRA", "NOITE"],
        "f": "TRANSFORMACAO_HUMOR"
    },
    "escorpião": {
        "n": "ESCORPIÃO",
        "c": "RAIZ",
        "d": "Proteção e Transformação Venenosa. Guardião de limiares, mestre da metamorfose. Símbolo de morte e renascimento.",
        "a": 0.4,
        "s": 0.9,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["TERRA", "FOGO"],
        "f": "PROTECAO_VENENOSA"
    },
    "camaleão": {
        "n": "CAMALEÃO",
        "c": "TERCEIRO OLHO",
        "d": "Adaptação e Percepção Multidimensional. Visão independente, capacidade de se transformar. Símbolo de mudança na África.",
        "a": 0.3,
        "s": 0.7,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["AR", "MUDANCA"],
        "f": "ADAPTACAO_VISUAL"
    },
    "girafa": {
        "n": "GIRAFA",
        "c": "GARGANTA",
        "d": "Visão Ampliada e Graça Elevada. Capacidade de ver além do horizonte imediato. Símbolo de elevação espiritual.",
        "a": 0.4,
        "s": 0.4,
        "i": 0.7,
        "p": "SOLAR",
        "e": ["AR", "TERRA"],
        "f": "VISAO_AMPLIADA"
    },
    "cobra": {
        "n": "COBRA",
        "c": "SACRO",
        "d": "Renovação e Poder Hipnótico. Capacidade de se renovar através da pele, fascínio mortal. Símbolo de sabedoria na Índia.",
        "a": 0.5,
        "s": 0.8,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["TERRA", "FOGO"],
        "f": "RENOVACAO_HIPNOTICA"
    },
    "andorinha": {
        "n": "ANDORINHA",
        "c": "CORAÇÃO",
        "d": "Migração e Renovação Cíclica. Retorno seguro ao lar, símbolo de lealdade e renovação. Mensageira da primavera.",
        "a": 0.3,
        "s": 0.4,
        "i": 0.7,
        "p": "SOLAR",
        "e": ["AR", "AGUA"],
        "f": "MIGRACAO_CICLICA"
    },
    "orca": {
        "n": "ORCA",
        "c": "PLEXO SOLAR",
        "d": "Família e Estratégia. Inteligência social complexa, caça cooperativa. Guardiã dos oceanos nas culturas nativas.",
        "a": 0.7,
        "s": 0.6,
        "i": 0.8,
        "p": "SOLAR",
        "e": ["AGUA", "GELO"],
        "f": "ESTRATEGIA_FAMILIAR"
    },
    "panda": {
        "n": "PANDA",
        "c": "CORAÇÃO",
        "d": "Paz e Equilíbrio Yin-Yang. Força gentil, símbolo de harmonia e diplomacia. Tesouro nacional da China.",
        "a": 0.2,
        "s": 0.3,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["TERRA", "BAMBU"],
        "f": "PAZ_EQUILIBRIO"
    },
    "rinoceronte": {
        "n": "RINOCERONTE",
        "c": "RAIZ",
        "d": "Força Bruta e Determinação. Poder focado em direção linear, resistência inabalável. Símbolo de força na África.",
        "a": 0.8,
        "s": 0.5,
        "i": 0.6,
        "p": "SOLAR",
        "e": ["TERRA", "FOGO"],
        "f": "FORCA_FOCADA"
    },
    "cervo": {
        "n": "CERVO",
        "c": "CORAÇÃO",
        "d": "Sensibilidade e Regeneração. Chifres que caem e renascem, conexão com ciclos naturais. Símbolo de espiritualidade celta.",
        "a": 0.3,
        "s": 0.5,
        "i": 0.8,
        "p": "LUNAR",
        "e": ["TERRA", "FLORESTA"],
        "f": "REGENERACAO_SENSIVEL"
    },
    "grifo": {
        "n": "GRIFO",
        "c": "COROA",
        "d": "Vigilância e Proteção de Tesouros. Guardião mítico entre o terrestre e o celestial. Símbolo de vigilância divina.",
        "a": 0.8,
        "s": 0.7,
        "i": 0.9,
        "p": "SOLAR",
        "e": ["AR", "TERRA", "FOGO"],
        "f": "VIGILANCIA_DIVINA"
    },
    "unicórnio": {
        "n": "UNICÓRNIO",
        "c": "COROA",
        "d": "Pureza e Magia Curativa. Chifre espiritual que purifica venenos, símbolo de inocência e poder. Criatura mítica de luz.",
        "a": 0.3,
        "s": 0.1,
        "i": 0.9,
        "p": "LUNAR",
        "e": ["LUZ", "ESPIRITO"],
        "f": "PUREZA_CURATIVA"
    },
    "quetzal": {
        "n": "QUETZAL",
        "c": "CORAÇÃO",
        "d": "Liberdade e Beleza Sacra. Ave sagrada que não sobrevive em cativeiro, símbolo de liberdade. Deus-serpente emplumado asteca.",
        "a": 0.4,
        "s": 0.5,
        "i": 0.9,
        "p": "SOLAR",
        "e": ["AR", "ESPIRITO"],
        "f": "LIBERDADE_SACRA"
    },
    "salmão": {
        "n": "SALMÃO",
        "c": "SACRO",
        "d": "Determinação e Sabedoria Ancestral. Nada contra a corrente para retornar às origens. Símbolo de sabedoria celta.",
        "a": 0.5,
        "s": 0.6,
        "i": 0.8,
        "p": "SOLAR",
        "e": ["AGUA", "TERRA"],
        "f": "DETERMINACAO_ANCESTRAL"
    },
    "lagarto": {
        "n": "LAGARTO",
        "c": "TERCEIRO OLHO",
        "d": "Renovação e Sonho. Capacidade de regenerar membros, conexão com o mundo dos sonhos. Símbolo de renovação no deserto.",
        "a": 0.3,
        "s": 0.7,
        "i": 0.7,
        "p": "LUNAR",
        "e": ["TERRA", "SOL"],
        "f": "RENOVACAO_SONHO"
    },
    "pavão": {
        "n": "PAVÃO",
        "c": "GARGANTA",
        "d": "Beleza e Espiritualidade. Olhos nas penas simbolizando visão cósmica, vaidade transformada. Símbolo de imortalidade.",
        "a": 0.5,
        "s": 0.4,
        "i": 0.8,
        "p": "SOLAR",
        "e": ["AR", "LUZ"],
        "f": "BELEZA_ESPIRITUAL"
    },
    "mocho": {
        "n": "MOCHO",
        "c": "COROA",
        "d": "Mistério e Silêncio Profético. Voo silencioso, visão noturna, mensageiro de presságios. Símbolo de mistério noturno.",
        "a": 0.4,
        "s": 0.8,
        "i": 0.9,
        "p": "LUNAR",
        "e": ["AR", "NOITE"],
        "f": "SILENCIO_PROFETICO"
    },
    "ganso": {
        "n": "GANSO",
        "c": "GARGANTA",
        "d": "Fidelidade e Viagem em Grupo. Lealdade ao parceiro por toda vida, migração em formação. Símbolo de vigilância romana.",
        "a": 0.4,
        "s": 0.3,
        "i": 0.6,
        "p": "SOLAR",
        "e": ["AR", "AGUA"],
        "f": "FIDELIDADE_MIGRACAO"
    },
    "búfalo": {
        "n": "BÚFALO",
        "c": "RAIZ",
        "d": "Abundância e Sacrifício. Fornecimento total para a comunidade, símbolo de gratidão. Sagrado para nativos americanos.",
        "a": 0.6,
        "s": 0.5,
        "i": 0.7,
        "p": "SOLAR",
        "e": ["TERRA"],
        "f": "ABUNDANCIA_SAGRADA"
    },
    "glutão": {
        "n": "GLUTÃO",
        "c": "RAIZ",
        "d": "Resiliência e Ferocidade. Pequeno mas destemido, sobrevive em condições extremas. Símbolo de tenacidade nórdica.",
        "a": 0.7,
        "s": 0.6,
        "i": 0.7,
        "p": "SOLAR",
        "e": ["TERRA", "GELO"],
        "f": "RESILIENCIA_FEROZ"
    },
    "tartaruga_marinha": {
        "n": "TARTARUGA MARINHA",
        "c": "SACRO",
        "d": "Navegação e Memória Oceânica. Retorna ao local exato do nascimento após décadas. Guia das profundezas.",
        "a": 0.3,
        "s": 0.4,
        "i": 0.9,
        "p": "LUNAR",
        "e": ["AGUA", "TERRA"],
        "f": "NAVEGACAO_ANCESTRAL"
    },
    "pelicano": {
        "n": "PELICANO",
        "c": "CORAÇÃO",
        "d": "Sacrifício e Nutrição. Alimenta os filhos com seu próprio sangue, símbolo de amor incondicional. Cristo na iconografia.",
        "a": 0.2,
        "s": 0.6,
        "i": 0.8,
        "p": "SOLAR",
        "e": ["AGUA", "AR"],
        "f": "SACRIFICIO_NUTRITIVO"
    },
    "esquilo": {
        "n": "ESQUILO",
        "c": "RAIZ",
        "d": "Preparação e Memória Prática. Armazena para o futuro, memória espacial excepcional. Símbolo de previdência.",
        "a": 0.4,
        "s": 0.3,
        "i": 0.6,
        "p": "SOLAR",
        "e": ["TERRA", "AR"],
        "f": "PREPARACAO_PRATICA"
    },
    "pinguim": {
        "n": "PINGUIM",
        "c": "CORAÇÃO",
        "d": "Adaptação e Dedicação Familiar. Sobrevive ao frio extremo, cuidado parental compartilhado. Símbolo de comunidade polar.",
        "a": 0.3,
        "s": 0.4,
        "i": 0.7,
        "p": "LUNAR",
        "e": ["AGUA", "GELO"],
        "f": "ADAPTACAO_FAMILIAR"
    },
    "guaxinim": {
        "n": "GUAXINIM",
        "c": "TERCEIRO OLHO",
        "d": "Curiosidade e Adaptação Urbana. Mestre da sobrevivência em ambientes humanos, inteligência prática. Trickster urbano.",
        "a": 0.5,
        "s": 0.7,
        "i": 0.7,
        "p": "LUNAR",
        "e": ["TERRA", "NOITE"],
        "f": "CURIOSIDADE_ADAPTATIVA"
    },
    "pegaso": {
        "n": "PÉGASO",
        "c": "COROA",
        "d": "Inspiração e Elevação Divina. Cavalo alado nascido do sangue de Medusa, símbolo da poesia e inspiração. Transporte dos heróis.",
        "a": 0.6,
        "s": 0.5,
        "i": 0.9,
        "p": "SOLAR",
        "e": ["AR", "FOGO", "ESPIRITO"],
        "f": "INSPIRACAO_DIVINA"
    }
};

// Torna disponível globalmente
if (typeof window !== 'undefined') {
    window.ANIMALS_DATA = ANIMALS_DATA;
}